### PR TITLE
Support Dynamic Module NGINX ≥ 1.9.11

### PR DESCRIPTION
**Pull request by denji**
Tested static and shared libraries:
----
```
$ # Run before: "nginx -V" copy "configure arguments: ****"
$ ./configure … --add-dynamic-module=…/nginx-vod-module && make -j4
$ ls ./objs/*vod*.so
./objs/ngx_http_vod_module.so
$ cp -v ./objs/ngx_http_vod_module.so {/usr/local,}/etc/nginx/modules/

$ ./configure … --add-module=…/nginx-vod-module && make -j4
```

etc/nginx/nginx.conf
---
```nginx
load_module modules/ngx_http_vod_module.so;

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
…
```

#### Refs

* https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/
* https://www.nginx.com/resources/wiki/extending/converting/
* https://www.nginx.com/blog/dynamic-modules-development/

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @denji,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Hi @denji 

Thank you for your contribution.
When building against nginx-1.8.0 (stable) I'm getting this error:
```
adding module in /root/erank/nginx-hls
checking for OpenSSL EVP library ... found
checking for clock_gettime() ... not found
checking for clock_gettime() in librt ... found
checking for libavcodec ... found
checking for libavfilter ... found
./configure: 237: [: =: unexpected operator
./configure: 241: [: =: unexpected operator
 + ngx_http_vod_module was configured
```
Adding double quotes around the if arguments fixes the error:
```
if [ "$ngx_module_link" = "DYNAMIC" ] ; then
```
But the module is still not included in the build.

I believe that in order to support compilation on older nginx modules, the config should look like the first sample here: https://www.nginx.com/resources/wiki/extending/converting/#
while your change looks more like the second sample on that page which assumes newer nginx versions.

Eran

**Comment by GoodGame** [comment]
Hello!

I tried build last vod module and nginx 1.9.14 with your pull request.
All fine, but when i try restart nginx i have error:

`[emerg] 10301#10301: dlopen() "/etc/nginx/modules/ngx_http_vod_module.so" failed (/etc/nginx/modules/ngx_http_vod_module.so: undefined symbol: av_frame_unref) in /etc/nginx/nginx.conf: 1`

Whats wrong?

**Comment by erankor** [comment]
Sounds like a mix of ffmpeg versions, nginx-vod was probably compiled against an ffmpeg version that has this function (otherwise you would have gotten a warning) but in runtime it loads an older so file that does not have it yet.
But, either way, you should note that we do not officially support dynamic compilation yet, I suggest you try to compile the module statically

**Comment by erankor** [comment]
Btw, easiest fix is to compile nginx-vod without ffmpeg, the only implication of this is that you won't be able to use audio filtering (e.g. change playback rate / volume) but all other features of this module will work fine

**Comment by GoodGame** [comment]
ffmpeg and devel was same versions:
 ffmpeg                   x86_64             2.8-4.el7.centos               @docker             9.8 M
 ffmpeg-devel             x86_64             2.8-4.el7.centos               @docker             9.0 M
 ffmpeg-libs              x86_64             2.8-4.el7.centos               @docker              23 M

I remove ffmpeg
Build .so and now i have:
2016/04/15 14:45:04 [emerg] 12830#12830: module "/etc/nginx/modules/ngx_http_vod_module.so" is not binary compatible in /etc/nginx/nginx.conf:1

**Comment by erankor** [comment]
Looking at the nginx source, this errors means that the module was not compiled with the same settings as the nginx core, e.g. the module was compiled with aio support while the nginx core was compiled without it. There are 30+ compilation settings that go into the module signature, and have to match in order for the module to load, see https://github.com/nginx/nginx/blob/c3aed0a23392a509f64b740064f5f6633e8c89d8/src/core/ngx_module.h

**Comment by denji** [comment]
Yes, we should copy the previous configuration using `nginx -V` from the string to the `configure arguments: *`.

**Comment by erankor** [comment]
@denji, I reviewed the updated version, I think it would be better to first assign the sources/deps to some variable specific to this module, and not directly to NGX_ADDON_DEPS. 
with the current implementation, if some other module uses the "old style" variables NGX_ADDON_DEPS/NGX_ADDON_SRCS, it would be added twice (once as part of nginx-vod and once on its own)
more specifically, I'm talking about something like this:
```
NGX_VOD_DEPS="$ngx_addon_dir/ngx_async_open_file_cache.h ...

NGX_VOD_SRCS="$ngx_addon_dir/ngx_async_open_file_cache.c ...

if ...
ngx_module_deps="$NGX_VOD_DEPS"
ngx_module_srcs="$NGX_VOD_SRCS"
else
NGX_ADDON_DEPS="$NGX_ADDON_DEPS $NGX_VOD_SRCS"
NGX_ADDON_SRCS="$NGX_ADDON_SRCS $NGX_VOD_SRCS"
fi
```
makes sense ?

**Comment by denji** [comment]
Prepared travis-ci tests, like everything looks great.

**Comment by erankor** [comment]
Looks good, one thing that you missed though - you need to remove NGX_ADDON_DEPS from the value of VOD_DEPS (and the same thing for SRCS), these values are added in the else of the if. 
Currently, NGX_ADDON_DEPS & NGX_ADDON_SRCS will be duplicated when the else is executed.

**Comment by denji** [comment]
@erankor /ping

**Comment by erankor** [comment]
@denji, did you see my comment above ? 

"Looks good, one thing that you missed though - you need to remove NGX_ADDON_DEPS from the value of VOD_DEPS (and the same thing for SRCS), these values are added in the else of the if. 
Currently, NGX_ADDON_DEPS & NGX_ADDON_SRCS will be duplicated when the else is executed."

**Comment by denji** [comment]
@erankor `NGX_ADDON_DEPS="$VOD_DEPS"`, `NGX_ADDON_SRCS="$VOD_SRCS"`

```diff
--- a/config
+++ b/config
@@ -76,9 +76,7 @@ if [ $ngx_found = yes ]; then
     CORE_LIBS="$CORE_LIBS $LIB_AV_FILTER $LIB_AV_UTIL"
 fi
 
…

-HTTP_AUX_FILTER_MODULES="$HTTP_AUX_FILTER_MODULES ngx_http_vod_module"
-
-NGX_ADDON_DEPS="$NGX_ADDON_DEPS                                     \
+VOD_DEPS="$NGX_ADDON_DEPS                                           \

-NGX_ADDON_SRCS="$NGX_ADDON_SRCS                                     \
+VOD_SRCS="$NGX_ADDON_SRCS                                           \

…

+if [ -n "$ngx_module_link" ]; then
+    ngx_module_type=HTTP_AUX_FILTER
+    ngx_module_name=ngx_http_vod_module
+    ngx_module_deps="$VOD_DEPS"
+    ngx_module_srcs="$VOD_SRCS"
+
+    . auto/module
+else
+    HTTP_AUX_FILTER_MODULES="$HTTP_AUX_FILTER_MODULES ngx_http_vod_module"
+    NGX_ADDON_DEPS="$VOD_DEPS"
+    NGX_ADDON_SRCS="$VOD_SRCS"
+fi
```

**Comment by erankor** [comment]
@denji I see you applied the change I requested, but you also applied another one that shouldn't have been - in the else block you have to append to NGX_ADDON_DEPS & NGX_ADDON_SRCS, you should not overwrite them, the latest version may remove other modules. 
Please just change the else to:
```
else
    HTTP_AUX_FILTER_MODULES="$HTTP_AUX_FILTER_MODULES ngx_http_vod_module"
    NGX_ADDON_DEPS="$NGX_ADDON_DEPS $VOD_DEPS"
    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $VOD_SRCS"
fi
```
this is the only thing needed to be changed.

**Comment by erankor** [comment]
For some reason I'm not getting any notification when you push changes, maybe it's because you rebase or something...
Anyway, merged, thanks !

**Pull request merged**
