### PR TITLE
Fix parse error and segfault in mapped simple vod stream.

### PR DESCRIPTION
**Pull request by ddunkin**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @ddunkin,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Thanks @ddunkin, can you explain why you added the memzero - which uninitialized field was accessed and in what scenario ?
In general, my focus in this module is to squeeze every bit of performance possible, so I'd prefer not to zero the whole struct, but rather fix any fields that are currently missing.

The second part of the patch makes perfect sense, I missed it in my tests because in our case the mapping response always matches `vod_path_response_prefix` / `vod_path_response_postfix`, so the code does not enter media_set_parse_json in case of a simple mapping.

**Comment by ddunkin** [comment]
I was getting a crash on https://github.com/kaltura/nginx-vod-module/blob/1.5.2/ngx_http_vod_module.c#L2886 because ```media_set.type``` was uninitialized.

**Comment by erankor** [comment]
I see... I went over all the fields now and this is indeed the only one that is missing, please change the pull so that instead of the memzero it will set result->type to MEDIA_SET_VOD inside if (params[MEDIA_SET_PARAM_DURATIONS] == NULL) in media_set_parse_json

Thanks

**Comment by erankor** [comment]
Merged, thanks !

**Pull request merged**
