### PR TITLE
Encrypt URL using ruby

### PR DESCRIPTION
**Pull request by ruby-fu-ninja**
Might be helpful for anyone writing rails apps.

Omitted PKCS#7 padding which is provided by default.

Reconciled results against encryptUrl.php

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @ruby-fu-ninja,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Thanks @ruby-fu-ninja! 
The PR looks good to me, please sign the CLA, we can't merge without it...

**Comment by ruby-fu-ninja** [comment]
all done @erankor - also just FYI the signing block canvas was positioned lower then the underline suggested, it took me a while to figure out how to draw the signature

Screen Shot 2021-03-22 at 10 46 40 AM

**Comment by erankor** [comment]
Merged, thanks!

**Pull request merged**
