### PR TITLE
Hls sample aes support

### PR DESCRIPTION
**Pull request by erankor**

### CODE REVIEW

**Comment by garybruckheimer** [comment]
in a first test, sample-aes works fine, great feature.

what about to add and uri for sample-aes?

we can set the key name with command:
vod_hls_encryption_key_file_name

looks like:
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="http://cdn.public.com/hlsenc/demo.mp4/keyfile.key"

but we cant seperate the key URI for this new method or the plain
AES-128, we only can we change it when we set the global the master_uri,
right?

I think it makes sense to seperate keys from content to add another
secure token between the keys and the real ts segments. this goes then
in a direction like the new apple fairplay encryption.

aes-uri can look like with path command, like:
vod_hls_encryption_master_key_server_uri (<- or whatever)

#EXT-X-KEY:METHOD=SAMPLE-AES,URI="http://mykeyserver.com/requestkey/keyXY.key?SESSION

what you think?

gary

**Comment by erankor** [comment]
Gary, thanks for your feedback !

The motivation behind this feature is indeed Fairplay, currently nginx-vod-module has 2 operation modes when it comes to encryption:
1. HLS AES-128 and SAMPLE-AES - the module generates the encryption key by hashing some identifier of the file (usually the uri or the content id) with a configured secret, and nginx-vod-module is also serving the key to the player
2. EDASH/CENC and MSS PlayReady - the module issues an HTTP request to a remote server and gets back a JSON with all the data it needs for packaging (encryption key, key id, pssh etc.). The serving of the keys (licenses) is not handled by the module

I'm not familiar with Fairplay yet, but my tendency at this point is to implement it using mode #2.

Makes sense ?

Eran

**Comment by garybruckheimer** [comment]
when we can set the uri path of the key, then you can specify fairplay
uri sheme, even for fairplay urls.

For FairPlay we first have to create a 128-bit CEK and 128-bit IV
(Initialization Vector). This is just a 32 bytes file with random bytes.
That´s all. The fairplay server will handle the shipment of the key for
internal iOS apps (not for safari desktop at the moment or any other
third-party server as far as i know).

I create the key with openssl cmd:
openssl rand 32 > fariplay.key

In m3u8 it will look like the same as sample-aes:
EXT-X-KEY:METHOD=SAMPLE-AES,URI="video.key"

A uri path field for the keyfile makes sense for all encryption modes i
think.

It´s the same as you setup an uri master path for the master manifest as
for the single manifest which contains the segments and the uri of the
keyfile itself.

Sure nginx-vod-module doenst handle the key shipping, but it would be
nice to define a absolute uri to a server that handles the keys, or?

my suggestion would for the keyfile uri in ngx_http_vod_hls.commands.h is:

{ ngx_string("vod_hls_encryption_key_absolute_master_uri"),
	NGX_HTTP_MAIN_CONF | NGX_HTTP_SRV_CONF | NGX_HTTP_LOC_CONF |
NGX_CONF_TAKE1,
	ngx_conf_set_str_slot,
	NGX_HTTP_LOC_CONF_OFFSET,
	BASE_OFFSET + offsetof(ngx_http_vod_hls_loc_conf_t,
m3u8_config.encryption_key_file_name),
	NULL },


what you think?
Gary


Am 29.09.15 um 08:39 schrieb erankor:

**Comment by erankor** [comment]
But the question is, what key will nginx-vod use for the encryption ?
Currently this key is generated by module, if we use an absolute URL for the key, IMHO it makes more sense that nginx-vod will get the key from some remote server instead of generating it.
This is more like the second mode I listed above - nginx-vod will hit some remote server and get back all the parameters, in this case, only key + key url

That's why I'm not sure it's worth adding such a parameter

**Comment by garybruckheimer** [comment]
you are right.

the key can be written in file not on request from the VOD module.
after generating the file it must upload to the/a keyserver / apple
fairplay key server. then absolute URI makes sense in your module.

i think thats the only way to implement fairplay correctly.

gary


Am 30.09.15 um 10:29 schrieb erankor:

**Comment by erankor** [comment]
Yeah, that can work, but my preference is to keep it aligned with how we handle the other DRMs now - nginx-vod will issue a query to some server, that server will verify the request came from nginx-vod (according to IP/request parameter etc.) and will return the encryption key + encryption key uri in JSON format.

This would be more convenient for us to work with since we don't need to copy any files, and the "DRM server" is the single source of truth when it comes to keys - everyone who needs a key asks that server (either nginx-vod or a player)

**Comment by garybruckheimer** [comment]
i fully understand...if needed users can create their own patch..



Am 30.09.15 um 13:40 schrieb erankor:

**Pull request merged**
