### PR TITLE
Upstream error handling

### LINKED ISSUE #468: Response code for missing remote mp4 file
Hello, I have an issue with response codes of nginx-vod-module. If I try to GET chunk or playlist for non existent remote mp4 file and nginx-vod-module returns 502 Bad Gateway instead of 404.

How to get "404" response for this case.

request:
`
http://myserver.example/video/XXX_,350,950,3800,.mp4.urlset/master.m3u8
`

kaltura config (simplified):
`    server {    
    	access_log /var/log/nginx/kaltura_access.log main;
    	error_log /var/log/nginx/kaltura_error.log;
 
        sendfile off;
 
        vod_mode remote;
    	vod_upstream_location /remote;
    
        vod_cache_buffer_size 16m;
	vod_metadata_cache metadata_cache 32768m;
        vod_response_cache response_cache 256m;
        vod_base_url ''; # for relative path

        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
    
        location ^~ /remote/ {
            internal;
            proxy_pass http://backend-video/;
            proxy_buffers 16 512k;
            proxy_buffer_size 512k;
	    proxy_set_header X-Limit $limit_header;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 http_404;
        }
 
        location ~* (.m3u8|.ts)$ {
    		vod hls;
    		expires 100d;
        }
        location ~* (.mpd|.m4f|.m4s|init[a-z0-9-]+.mp4)$ {
    		vod dash;
    		expires 100d;
        }
    }

    upstream backend-video {
        server 1.1.1.1;
        server 2.2.2.2;

        server 3.3.3.3 backup;
        server 4.4.4.4 backup;
    }

`

kaltura_error.log:
`
2016/11/25 02:11:14 [error] 10110#10110: *73546194 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 5.5.5.5, server: , request: "GET /video/XXX_,350,950,3800,.mp4.urlset/master.m3u8 HTTP/1.1"
`
kaltura_access.log:
`
5.5.5.5 [25/Nov/2016:02:11:14 +0300] GET "http://myserver.example/video/XXX_,350,950,3800,.mp4.urlset/master.m3u8" HTTP/1.1 502
`

All "backend-video" upstreams return 404.

Thank you!

### PR DESCRIPTION
**Pull request by SebastienChauvin**
- propagate upstream http code when upstream returns NGX_HTTP_BAD_REQUEST, NGX_HTTP_NOT_FOUND, NGX_HTTP_FORBIDDEN, NGX_HTTP_GONE
- include upstream uri in error log

Fix #468

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @SebastienChauvin,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by SebastienChauvin** [comment]
Hello @erankor, did I miss something ? Is there a preferred way to have a discussion around the PR ?

**Comment by erankor** [comment]
1. I didn't understand why you chose those 4 specific status codes. If anything, I'd add a configurable list of status codes, as I did in our live packager - https://github.com/kaltura/media-framework/tree/master/nginx-pckg-module#pckg_pass_codes
2. I'm quite sure the URI is already printed by the base logger, I think only the status code should be logged here
3. The indentation doesn't match the existing code

**Comment by SebastienChauvin** [comment]
Thanks for the feedback

**Pull request closed without merging**
