### PR TITLE
add HLS option vod_hls_force_master_separate_audio_video

### PR DESCRIPTION
**Pull request by tim-lansen**
#644 Have made changes according to issue comments

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @tim-lansen,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Thanks @tim-lansen, a couple of comments:
1. Better save `adaptation_sets.count[ADAPTATION_TYPE_AUDIO] > 0 && adaptation_sets.total_count > 1` in a local boolean (alternative_audio), since it repeats a few times in this function
2. There are still a couple of instances of `count[ADAPTATION_TYPE_AUDIO] > 1` in that file that need to be changed
3. I prefer to call the setting force_unmuxed_segments (instead of force_master_separate_audio_video)
4. Please sign the CLA, we can't merge without it

**Comment by tim-lansen** [comment]
I've added the variable 'alternative_audio'.
Is it necessary to replace other instances of `count[ADAPTATION_TYPE_AUDIO] > 1`?

**Comment by erankor** [comment]
I believe it is, the problematic case is the simple case of 1 audio + 1 video with this new setting enabled -
1. If you don't change this occurrence - https://github.com/tim-lansen/nginx-vod-module/blob/13c327d950ece36207a67dd7f3ff57a218dc092d/vod/hls/m3u8_builder.c#L874, the EXT-STREAM-INF tag won't have an AUDIO attribute, and will therefore play video only.
2. If you don't change this occurrence - https://github.com/tim-lansen/nginx-vod-module/blob/13c327d950ece36207a67dd7f3ff57a218dc092d/vod/hls/m3u8_builder.c#L1150, the CODECS attribute will contain only the video codec.

But anyway, I suggest you try it out (just a take a simple mp4 with audio + video) and check whether you are indeed seeing the two issues that I wrote.

**Comment by tim-lansen** [comment]
@erankor yes, it's all as you said )

**Comment by erankor** [comment]
@tim-lansen, 2 more comments -
1. please move the declaration of alternative_audio to the beginning of the function, that is the convention in this module (put it next to bool_t iframe_playlist)
2. please change the name of the setting, as I requested above (force_unmuxed_segments), both the name of the struct field and the name of the conf param

**Comment by tim-lansen** [comment]
@erankor oh, sorry my obliviousness... done

**Comment by erankor** [comment]
Merged, thanks!

**Comment by tim-lansen** [comment]
Thank you =)
In future, should one also edit README?

**Comment by erankor** [comment]
Yes :) I usually remember to add it, forgot in this case... anyway, I'll add it

**Pull request merged**
