### PR TITLE
Update audio_filter.c

### PR DESCRIPTION
**Pull request by itpp16**
formal parameters different from declaration

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @itpp16,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by itpp16** [comment]
Sorry but we don't agree with this approach, we contribute to github for free from feedback from our porting team.

**Comment by zoharbabin** [comment]
@itpp16
There might be a misunderstanding, you're not asked to pay for anything. However a cla agreement is required to accept your code to the project.
Please let us know if you have any questions, I'd be happy to also discuss over Skype z.Babin . Thanks!

**Comment by jessp01** [comment]
@itpp16 - ping

**Comment by itpp16** [comment]
Signing any agreement is not going to happen, sorry.

**Pull request closed without merging**
