### PR TITLE
Support ASS/SSA captions/subtitle file inputs, tested on HLS outputs

### PR DESCRIPTION
**Pull request by rmikhael**
First try here.

Main changes are addition of 3 file under directory vod/subtitles/
- ass_parse.c is code mostly copied from libass, and modified/reduced/adjusted for the limited set of possible inputs supported for this project. PLEASE revise the MIT license used in this file.
- ass_format.c and ass_format.h are newly added files, that implement the WebVTT segment/playlist building for the output. These files can follow the same license as the rest of the project. Naming of structures here follow the ASS naming conventions (track, style, event).
- addition of these 3 files to build/make files as needed. Addition of the new input format support into media enums. Update of Readme.md.
- Rest of the files are mostly merging of recent nginx-vod-module changes. 

These changes were tested with 8 different languages per mp4, using HLS multi-track URLs in local and remote modes. Arabic is the only rtl language tested, and detection/handling might not be optimal for the long-term.
Not tested in Dash, but should work similarly. 
Tested for more than a month in production at crunchyroll. No memory leaks or crashes observed.

Styles are not yet correctly supported on all 4 browsers, VLC, shaka players. There are open bug/feature reports on all of them that I am following. Styles can be fully supported in the output, by enabling #define ASSUME_STYLE_SUPPORT.

Please review and provide me with feedback / questions. We would like to contribute this to the community, to get some commonality of features supported by the browsers.

I can provide sample input/output files if needed.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @rmikhael,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Thanks @rmikhael.

From a quick look -
1. As you wrote, the pull has many unrelated changes, you should create a new pull from a fresh master, so that it will have only your changes.
2. I would prefer to link against libass instead of pulling it in, it can be an optional dependency as we have with libxml and dfxp, for example. Is there any reason not to use this approach?
3. The code here uses several different conventions, maybe some of it is due to libass, but I think that many cases are not. Anything that is not part of libass has to conform to the conventions of the rest of the module.

**Comment by rmikhael** [comment]
Thanks a lot for the prompt response Eran. Here are my responses:

1. Will do a clean pull, merge, and new PR.

3. Will try to replace all the camelCase names to underscores. Are there any other coding conventions I am missing? I tried to use the vod_xxx() functions as much as possible, instead of regular string and memory C functions. I also used the logging functions used in other vod/subtitle files. Please let me know main things to change, so I don't redo a lot of rewriting.

2. Many reasons I didn't want to link to libass, here is what I remember:
a) libass has a ton of features that we don't care about for our purposes, like Fonts, karaoke, clipping, blurs, fades, moving, rotations, scrolling up and down, bitmaps, transition effects, shadows, all inline-tags (and these are really really numerous)... etc. They all come with their initialization steps like directories, callback functions... We didn't need all that. 
b) given that libass output is rendering, not manipulated text, the steps and timing and what needs to be stored in the intermediate ass_track, ass_style, ass_event are a lot different. It was much easier to keep what I need and discard what I don't, than to try and convert every call to the renderer into some post-processing step on the text stored. I am not even sure it is doable.
c) I wanted to control all memory allocations and freeing, for testability and for allocating from the pool in case of post-error clean-up.
d) logging and debugging code needs to be done the nginx way. Much easier to debug a local file conforming, than to try and debug an external library.
e) use of destructive parsing (the code inserts a '\0' at the end of every line, before it parses its text. vod module calls the parse_memory function twice; once to get the duration and figure out the start/end of the segment, and once for actual parsing of the events. 

This code doesn't handle all legal ASS features, only a small subset that is common in our files. But given that Animation is one of the major users of high-quality fancy subtitles, I am guessing this limited set is a good start for most applications. Missing features can be requested and implemented one-by-one. 
Not to say that in the future we couldn't link to libass and support all features supported, it is just not needed for my company, so will be very hard to get resources allocated. We are sharing the limited set that we invested in handling/preserving, and hoping the community can add to that over time.

This same discussion will be repeated in the future, as we are adding SCC->WebVTT support as well. Of course there are public open-source libraries that read SCC from a bitstream (with all the parsing needed) but we only need to parse SCC from a text file, which makes most of the code unusable for that purspose.

**Comment by rmikhael** [comment]
Silly question from a novice github'er: If I checkout kaltura's master to a private branch, I don't have permission to push to the private branch. How do I pull the latest master and create a PR with the merged changes?

**Comment by ESPNMichaelKidd** [comment]
> Silly question from a novice github'er: If I checkout kaltura's master to a private branch, I don't have permission to push to the private branch. How do I pull the latest master and create a PR with the merged changes?

@rmikhael push to a branch in your own fork, and then you'll be able to issue the PR from there

**Pull request closed without merging**
