### PR TITLE
Add directive to disable iframe playlists

### PR DESCRIPTION
**Pull request by Euphe**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @Euphe,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Thanks for this pull, a few comments - 
1. Instead of having a 'disable' param, I'd prefer to have an 'enable' param with a default value of true. That would be more in line with the existing params. I think a good name for the parameter is `vod_hls_output_iframes_playlist`
2. There's no need to add the field to ngx_http_vod_hls_loc_conf_t, m3u8_config_t is enough
3. Non matching indent in ngx_conf_merge_value (spaces instead of tab)

**Comment by erankor** [comment]
Few follow up comments -
1. I see you used `ngx_conf_set_str_slot`, it should be `ngx_conf_set_flag_slot`. Please make sure to test it with on and off, because I can't see how it can work as it is now...
2. Please update the readme description (it still applies to the 'disable' parameter)
3. We now have the spaces/tab issue in `output_iframes_playlist = NGX_CONF_UNSET;`

**Comment by Euphe** [comment]
Tested, works with both on and off options.

**Comment by erankor** [comment]
Merged, thanks!

**Pull request merged**
