### PR TITLE
add vod_hls_force_sequence_index directive

### PR DESCRIPTION
**Pull request by xmedia-systems**
Solution for #973

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @xmedia-systems,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Thanks @xmedia-systems, I think a better solution would be to move the param to global scope (not HLS specific) and simply do something like -
```
if (conf->force_sequence_index) 
{
media_set->has_multi_sequences = TRUE; 
}
```
before the call to handle_metadata_request in ngx_http_vod_handle_metadata_request (need to make sure to push the initialization of `conf` earlier for this to work).
This solution will require less changes & it will cover DASH & HDS in addition to HLS.
(I didn't try it, but should work...)

Other than that, you should document the new parameter in the readme.

**Comment by xmedia-systems** [comment]
Thanks @erankor, please take a look at my updated pull request. You're right about storing this config in media_set and thus making it easier to propagate (also for DASH & HLS). As you suggested I'm setting the has_multi_sequences field, but maybe we need a new field there (like force_sequence_index) to prevent confusion in the future. Right now I don't see any side effects however

**Comment by erankor** [comment]
@xmedia-systems, why do we need to set it in 3 places? isn't it enough to do it only where I wrote above?

**Comment by xmedia-systems** [comment]
Hi @erankor, 
not having your global overview of the code, I found all 3 locations, where `media_set` gets initialized. From there I followed the call-chain up until where the configuration is available. I'm still not sure if a metadata_request is the only reason for `media_set` initialization: one chain starts for example at `ngx_http_vod_map_source_clip_state_machine`

**Comment by erankor** [comment]
From what I saw, this value is only read from manifest requests (=metadata_request in this context).
So I'd rather go with my original suggestion, assuming it works as expected...

**Comment by xmedia-systems** [comment]
I changed my patch again following your suggestion. My tests work well.

**Comment by erankor** [comment]
Merged, thanks!

**Pull request merged**
