### PR TITLE
Support ASS/SSA captions/subtitle file inputs, tested on HLS outputs

### PR DESCRIPTION
**Pull request by rmikhael**
Second try after merging/pushing Kaltura's latest master.

Main changes are addition of 3 file under directory vod/subtitles/:
- ass_parse.c is code mostly copied from libass, and modified/reduced/adjusted for the limited set of possible inputs supported for this project. PLEASE revise the MIT license used in this file.
- ass_format.c and ass_format.h are newly added files, that implement the WebVTT segment/playlist building for the output. These files can follow the same license as the rest of the project. Naming of structures here follow the ASS naming conventions (track, style, event).
- addition of these 3 files to build/make files as needed. Addition of the new input format support into media enums. Update of Readme.md.

These changes were tested with 8 different languages per mp4, using HLS multi-track URLs in local and remote modes. Arabic is the only rtl language tested, and detection/handling might not be optimal for the long-term.
Not tested in Dash, but should work similarly.
Running for more than a month in production at crunchyroll. No memory leaks or crashes observed.

Styles are not yet correctly supported on all 4 browsers, VLC, shaka players. There are open bug/feature reports on all of them that I am following. Styles can be modestly supported in the output, by enabling #define ASSUME_STYLE_SUPPORT.

Many reasons we didn't want to link to libass:
a) libass has a ton of features that we don't care about for our purposes, like Fonts, karaoke, clipping, blurs, fades, moving, rotations, scrolling up and down, bitmaps, transition effects, shadows, all inline-tags (and these are really really numerous)... etc. They all come with their initialization steps like directories, callback functions... We didn't need all that.
b) given that libass output is rendering, not manipulated text, the steps and timing and what needs to be stored in the intermediate ass_track_t, ass_style_t, ass_event_t are a lot different. It was much easier to keep what I need and discard what I don't, than to try and convert every renderer setting change into some post-processing step on the text stored. I am not even sure it is doable.
c) I wanted to control all memory allocations and freeing, for testability and for allocating from the pool in case of post-error clean-up.
d) logging and debugging code needs to be done the nginx way. Much easier to debug a local file conforming, than to try and debug an external library.
e) use of destructive parsing (the code inserts a '\0' at the end of every line, before it parses its text. vod module calls the parse_memory function twice; once to get the duration and figure out the start/end of the segment, and once for actual parsing of the events.

This code doesn't handle all legal ASS features, only a small subset that is common in our files. But given that Animation is one of the major users of high-quality fancy subtitles, I am guessing this limited set is a good start for most applications. Missing features can be requested and implemented one-by-one.

### CODE REVIEW

**Comment by rmikhael** [comment]
Sample input output (with #define ASSUME_STYLE_SUPPORT enabled):
`[Script Info]
Title: English (US)
Original Script: fwpc
Original Translation: 
Original Editing: 
Original Timing: 
Synch Point: 
Script Updated By: 
Update Details: 
ScriptType: v4.00+
Collisions: Normal
PlayResX: 640
PlayResY: 360
Timer: 0.0000
WrapStyle: 0

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: sign_2067_43_High_School_Divi,Times New Roman,14,&H003E484E,&H000000FF,&H00F5FBFD,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,7,0055,0365,0018,1
Style: sign_2067_44_The_Third_Seat,Times New Roman,30,&H00D744A1,&H000000FF,&H00F8FFFE,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,7,0275,0030,0018,1
Style: sign_2067_45_Megishima_Tosuke,Times New Roman,30,&H00424746,&H000000FF,&H00F6FAFB,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,1,0130,0030,0110,1

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,0:00:00.00,0:00:07.35,sign_2067_43_High_School_Divi,Sign 0127,0000,0000,0000,,High School Division, 3rd Year
Dialogue: 0,0:00:00.00,0:00:07.35,sign_2067_44_The_Third_Seat,Sign 0127,0000,0000,0000,,The Third Seat
Dialogue: 0,0:00:00.00,0:00:07.35,sign_2067_45_Megishima_Tosuke,Sign 0127,0000,0000,0000,,Megishima Tosuke
Dialogue: 0,0:00:10.00,0:00:13.00,Default,Sign 0127,0000,0000,0000,,This text should show with Strike Through.

`
$curl -X GET -v 'http://localhost:80/short.ass/seg-1.vtt'
`WEBVTT

STYLE
::cue(v[voice="Default"]) {
color: #ffffff00;
font-family: "Trebuchet MS", sans-serif;
font-size: 024px;
text-shadow: #00000000 -2px 0px, #00000000 0px 2px, #00000000 0px -2px, #00000000 2px 0px, #00000000 1px 1px 0px;
}

STYLE
::cue(v[voice="sign_2067_43_High_School_Divi"]) {
color: #4e483e00;
font-family: "Times New Roman", sans-serif;
font-size: 014px;
text-shadow: #fdfbf500 -3px 0px, #fdfbf500 0px 3px, #fdfbf500 0px -3px, #fdfbf500 3px 0px, #00000000 0px 0px 0px;
}

STYLE
::cue(v[voice="sign_2067_44_The_Third_Seat"]) {
color: #a144d700;
font-family: "Times New Roman", sans-serif;
font-size: 030px;
text-shadow: #fefff800 -3px 0px, #fefff800 0px 3px, #fefff800 0px -3px, #fefff800 3px 0px, #00000000 0px 0px 0px;
}

STYLE
::cue(v[voice="sign_2067_45_Megishima_Tosuke"]) {
color: #46474200;
font-family: "Times New Roman", sans-serif;
font-size: 030px;
text-shadow: #fbfaf600 -3px 0px, #fbfaf600 0px 3px, #fbfaf600 0px -3px, #fbfaf600 3px 0px, #00000000 0px 0px 0px;
}

STYLE
::cue(.strike) {
  text-decoration: solid line-through;
}

c0000000
00:00:00.000 --> 00:00:07.350 position:008% size:060% line:01 align:left
<v sign_2067_43_High_School_Divi><b>High School Division, 3rd Year</b>

c0000001
00:00:00.000 --> 00:00:07.350 position:042% size:042% line:01 align:start
<v sign_2067_44_The_Third_Seat><b>The Third Seat</b>

c0000002
00:00:00.000 --> 00:00:07.350 position:020% size:048% line:09 align:start
<v sign_2067_45_Megishima_Tosuke><b>Megishima Tosuke</b>

c0000003
00:00:10.000 --> 00:00:13.000 position:050% size:096% line:12 align:center
<v.strike Default>This text should show with Strike Through.

`
with a 12 second segment duration.

**Comment by joaoserra** [comment]
Hi @rmikhael,

Just one curiosity on your use case: Why don't you simply convert the ass file to WebVTT? Given that subtitle file sizes are very small, having two copies of the subtitles for each language (one in ASS, another in WebVTT) shouldn't be a burden on your storage.

**Comment by erankor** [comment]
@rmikhael, I reviewed this pull in more detail, it is still very far from what we require, and will not be merged.
Some of the issues I'm seeing fall under the category of conventions/style (variable names, spaces, new lines, comments etc.), and some are more fundamental issues that relate to patterns that we use vs. ones that we don't, and overall robustness of the code.
For example, I've now downloaded some random ASS sample, and got a division-by-zero segfault here - 
https://github.com/kaltura/nginx-vod-module/pull/924/files#diff-1038ab4af3d9b459960ad38aff2f09abR693
It is possible that the sample is invalid, but the code shouldn't crash, no matter what input file it gets.

You can still, of course, keep patching your local source with this feature - the interface of 'media formats' is unlikely to change, and I doubt you'll have trouble making it work with future versions.

**Comment by rmikhael** [comment]
Hi @erankor, 
thanks for the feedback. But please provide me with more details.

We are not in any rush open-sourcing this, and we are willing to put more time into it to get it up to expectations. The main reason we want it open sourced is to get feedback from the community for what is missing, and to get a united front while asking browsers/players to support certain WebVTT features.

1) Are there any specific (published) guidelines for the coding styles/conventions/spaces. I tried imitating the rest of the subtitles directory as much as I could. Please let me know what is needed, as I can't comply with an unknown set of rules.
2) Yes, the file you used is invalid ASS, as it is missing 2 required fields. We didn't worry too much about error robustness yet, because all of our 50K+ mezzanines are revised by COPs and QA automation upon receipt from partners. So in our case, we would never receive an invalid ASS file in the packager.
That said, we are more than happy to increase the tolerance and robustness in the code. Any set of test files in mind? We could modify the code to ensure any missing fields don't crash the code, but what else? What is required behavior if any of the fields is an unintelligible string? How much error resilience is required, and how to test it?

Any feedback is appreciated.

**Comment by erankor** [comment]
@rmikhael, I'll be completely honest with you, my concern is that it will take many iterations, and consume a lot of my time, for a feature that is extremely low priority for us.
Regarding your questions -
1. Unfortunately, the conventions are not documented, but I believe the code of the entire module is very coherent in this regard.
2. Regarding robustness/resilience - in our system, anyone can upload a media file (video/audio/subtitles/...) that will ultimately get packaged by this module. We have done our best to ensure that no corrupt or even malicious file could crash or server or worse - allow code execution. We're not trying to make the packaging succeed regardless of errors, failing the request for the tiniest incompatibility is perfectly ok. 

Anyway, since I already briefed through the code when I posted my previous comment, here are a few of the things I've seen - 
1. Spaces - before and after operators, e.g. x += y not x+=y. 
2. New lines for braces
3. Indentation should use tabs. Large indentation should be avoided - in some cases this can be achieved by reversing ifs (e.g. if (x) { ... } becomes if (!x) { continue; }) in other cases it may be done by moving the internal code to a function.
4. Variable names should be lower case with underscores (some of the code is already like that, some is not). When there is a matching core-nginx convention for the name, I'm using it, e.g. `p` usually means a running pointer. But in other cases, I'm using longer more informative names.
5. Booleans are considered zero vs. nonzero, we are not checking for if (x == true), but either if (x) or if (!x)
6. Comments are used only when there is something non-trivial to document
7. Single variable definition per line / single code statement per line
8. All the tables at the beginning of the file can be arranged better using the x-macros pattern (like languages_x.h)
9. split_event_text_to_chunks should use a running pointer instead of incrementing dstidx, this will enable the use of vod_copy, and more in general, the return value of vod_sprintf / vod_copy can be used to advance the pointer instead of all these +='s

**Pull request closed without merging**
