### PR TITLE
CI: use GitHub Actions

### PR DESCRIPTION
**Pull request by JoelLinn**
Since travis is dead, use GitHub Actions.

I am not a huge fan of them (e.g. they parse the workflow `stdout` for commands an then execute them) but it should be fine if one disables write access in the settings and doesn't use it to publish binaries.

The tests are hard to integrate and the `C` tests won't even compile any more :/

### CODE REVIEW

**Comment by JoelLinn** [comment]
Ping @jessp01 since you have done the travis scripts.

**Comment by jessp01** [comment]
Hello @JoelLinn ,

Thank you for your pull. I agree with your note about GH actions. I'll note, however, that Travis CI is still functional. They've deprecated travis-ci.org in favour of travis-ci.com but the latter is operational, see:
https://app.travis-ci.com/github/kaltura/nginx-vod-module/builds

Having said that, alas, Travis (which I like far better than GH actions) has become a lot slower so, I do not object to moving the CI to GH actions.

I do have a few comments, however:

https://github.com/kaltura/nginx-vod-module/pull/1301/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR70
I'd say let's remove this commented block.
 
https://github.com/kaltura/nginx-vod-module/pull/1301/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR75
 
Unless you intend to actually add a test here (which I am in favour of), let's remove that as well.

Thanks again,

**Comment by JoelLinn** [comment]
Travis now has a very tight _free_ budget for CI time. To my experience it is spend incredibly fast and they are unreachable (to get more free credits according to their open source policy...).

I moved my projects (that produce binaries) to drone.io, mainly because the server software is open source - just in case.

I will remove the two dummy steps. I will add the bitset test as part of #1290 once this is merged.

**Comment by JoelLinn** [comment]
I removed the two redundant steps.
[Pipeline on my repo](https://github.com/JoelLinn/nginx-vod-module/actions/runs/1177635774)

**Comment by jessp01** [comment]
Thanks, @JoelLinn. Merged:)

**Pull request merged**
