### PR TITLE
Fix Python syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
Python 2 died 768 days ago on 1/1/2020 so upgrade the code to remove Python Syntax Errors.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @cclauss,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Python 2 will forever be in our hearts, may it rest in peace... :(
PR looks good, please sign the CLA, and we're good to merge

**Comment by cclauss** [comment]
CLA signed.

**Comment by erankor** [comment]
Merged, thanks!

**Comment by erdi2202** [comment]
> Python 2 will forever be in our hearts, may it rest in peace... :( PR looks good, please sign the CLA, and we're good to merge



> Python 2 will forever be in our hearts, may it rest in peace... :( PR looks good, please sign the CLA, and we're good to merge

Hello, I am trying to play hls videos on my storage server with the kaltura remote module, but I could not succeed. When I run the Kaltura vod module locally on the storage server, the url
 = http://d1.rectvideo.tk/hls/d1/cdn4/movies/hd/mp4/12yillik.mp4/index.m3u8 and it works fine. But with my load balancer server

upstream kalapi {
      server 95.217.190.50;
      server 95.217.176.134;
      server 95.217.177.154;
   }

In this way, when I connect to storage servers, it works as mp4 but not as hls.

**Comment by erdi2202** [comment]
kaltura.conf
`user  kaltura;
worker_processes  auto;


pid		/var/run/nginx.pid;

events {
	worker_connections  1024;
	multi_accept on;
	use epoll;
}

http {
	upstream kalapi {
		server d11.rectvideo.tk:80;
	}
		
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" "$http_user_agent" "-" - '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';



	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

# vod settings
		vod_mode remote;
		vod_upstream_location /kalapi;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

	server {
		listen 80;
		server_name 2.rectvideo.tk;
		include /etc/nginx/conf.d/kaltura.conf;
		
			location ^~ /kalapi/ {
			internal;
			proxy_pass http://kalapi/;
			proxy_set_header Host $http_host;
		}

	}

}

   
`

**Comment by erdi2202** [comment]
nginx.con file


user  kaltura;
worker_processes  auto;


pid		/var/run/nginx.pid;

events {
	worker_connections  1024;
	multi_accept on;
	use epoll;
}

http {
	upstream kalapi {
		server d11.rectvideo.tk:80;
	}
		
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" "$http_user_agent" "-" - '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';



	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

# vod settings
		vod_mode remote;
		vod_upstream_location /kalapi;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

	server {
		listen 80;
		server_name 2.rectvideo.tk;
		include /etc/nginx/conf.d/kaltura.conf;
		
			location ^~ /kalapi/ {
			internal;
			proxy_pass http://kalapi/;
			proxy_set_header Host $http_host;
		}

	}

}

**Comment by erdi2202** [comment]
kaltura.conf file



		
		# static files (crossdomain.xml, robots.txt etc.) + fallback to api
		location / {
			root   @STATIC_FILES_PATH@;
			try_files $uri @api_fallback;
		}

		# nginx status page
		location /nginx_status {
			stub_status on;
			access_log off;
		}

		# vod status page
		location /vod_status {
			vod_status;
			access_log off;
		}
		
		# internal location for vod subrequests
		location /kalapi_proxy/ {
			internal;
			proxy_pass http://kalapi/;
			proxy_set_header Host $http_host;
		}
		
		# serve flavor progressive (clipFrom/To are not supported with 'vod none' so they are proxied)
		location ~ ^/p/\d+/(sp/\d+/)?serveFlavor/((?!clipFrom)(?!clipTo).)*$ {
			vod none;

			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}
		
		# serve flavor HLS
		location /hls/p/\d+/(sp/\d+/)?serveFlavor/ {
			vod hls;
			vod_bootstrap_segment_durations 2000;
			vod_bootstrap_segment_durations 2000;
			vod_bootstrap_segment_durations 2000;
			vod_bootstrap_segment_durations 4000;

			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			add_header Access-Control-Allow-Headers "*";
			add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
			add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
			add_header Access-Control-Allow-Origin "*";
			expires 100d;
		}
		
		# serve flavor DASH
		location ~ ^/dash/p/\d+/(sp/\d+/)?serveFlavor/ {
			vod dash;
			vod_segment_duration 4000;
			vod_bootstrap_segment_durations 3500;
			vod_align_segments_to_key_frames on;
			vod_dash_manifest_format segmenttemplate;
			
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			add_header Access-Control-Allow-Headers "origin,range,accept-encoding,referer";
			add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
			add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
			add_header Access-Control-Allow-Origin "*";
			expires 100d;
		}
		
		# serve flavor HDS
		location ~ ^/hds/p/\d+/(sp/\d+/)?serveFlavor/ {
			vod hds;
			vod_segment_duration 6000;
			vod_align_segments_to_key_frames on;
			vod_segment_count_policy last_rounded;
			
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			add_header Access-Control-Allow-Origin "*";
			expires 100d;
		}

		# serve flavor MSS
		location ~ ^/mss/p/\d+/(sp/\d+/)?serveFlavor/ {
			vod mss;
			vod_segment_duration 4000;
			vod_manifest_segment_durations_mode accurate;
			
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}	
		
		# all unidentified requests fallback to api (inc. playManifest)
		location @api_fallback {
			proxy_pass http://kalapi;
			proxy_set_header Host $http_host;
		}
		
		#error_page  404			  /404.html;

		# redirect server error pages to the static page /50x.html
		#
		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   html;
		}

                location /dashme {
                        open_file_cache off;
                        root /var/tmp;
                        add_header Cache-Control no-cache;
                        # To avoid issues with cross-domain HTTP requests (e.g. during development)
                        add_header Access-Control-Allow-Origin *;
                }
                location /hlsme {
                        open_file_cache off;
                        types {
                                application/vnd.apple.mpegurl m3u8;
                        }
                        root /var/tmp;
                        add_header Cache-Control no-cache; # Prevent caching of HLS fragments
                        add_header Access-Control-Allow-Origin *; # Allow web player to access our playlist
                }

**Comment by erdi2202** [comment]
nginx.conf file


user  kaltura;
worker_processes  auto;


pid		/var/run/nginx.pid;

events {
	worker_connections  1024;
	multi_accept on;
	use epoll;
}

http {
	upstream kalapi {
		server d11.rectvideo.tk:80;
	}
		
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" "$http_user_agent" "-" - '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';



	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

		vod_mode remote;
		vod_upstream_location /kalapi;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

	server {
		listen 80;
		server_name 2.rectvideo.tk;
		include /etc/nginx/conf.d/kaltura.conf;
		
			location ^~ /kalapi/ {
			internal;
			proxy_pass http://kalapi/;
			proxy_set_header Host $http_host;
		}

	}

}

**Comment by erdi2202** [comment]
kaltura.conf file

	# static files (crossdomain.xml, robots.txt etc.) + fallback to api
	location / {
		root   @STATIC_FILES_PATH@;
		try_files $uri @api_fallback;
	}

	# nginx status page
	location /nginx_status {
		stub_status on;
		access_log off;
	}

	# vod status page
	location /vod_status {
		vod_status;
		access_log off;
	}
	
	# internal location for vod subrequests
	location /kalapi_proxy/ {
		internal;
		proxy_pass http://kalapi/;
		proxy_set_header Host $http_host;
	}
	
	# serve flavor progressive (clipFrom/To are not supported with 'vod none' so they are proxied)
	location ~ ^/p/\d+/(sp/\d+/)?serveFlavor/((?!clipFrom)(?!clipTo).)*$ {
		vod none;

		add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		expires 100d;
	}
	
	# serve flavor HLS
	location /hls/p/\d+/(sp/\d+/)?serveFlavor/ {
		vod hls;
		vod_bootstrap_segment_durations 2000;
		vod_bootstrap_segment_durations 2000;
		vod_bootstrap_segment_durations 2000;
		vod_bootstrap_segment_durations 4000;

		add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		add_header Access-Control-Allow-Headers "*";
		add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
		add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
		add_header Access-Control-Allow-Origin "*";
		expires 100d;
	}
	
	# serve flavor DASH
	location ~ ^/dash/p/\d+/(sp/\d+/)?serveFlavor/ {
		vod dash;
		vod_segment_duration 4000;
		vod_bootstrap_segment_durations 3500;
		vod_align_segments_to_key_frames on;
		vod_dash_manifest_format segmenttemplate;
		
		add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		add_header Access-Control-Allow-Headers "origin,range,accept-encoding,referer";
		add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
		add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
		add_header Access-Control-Allow-Origin "*";
		expires 100d;
	}
	
	# serve flavor HDS
	location ~ ^/hds/p/\d+/(sp/\d+/)?serveFlavor/ {
		vod hds;
		vod_segment_duration 6000;
		vod_align_segments_to_key_frames on;
		vod_segment_count_policy last_rounded;
		
		add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		add_header Access-Control-Allow-Origin "*";
		expires 100d;
	}

	# serve flavor MSS
	location ~ ^/mss/p/\d+/(sp/\d+/)?serveFlavor/ {
		vod mss;
		vod_segment_duration 4000;
		vod_manifest_segment_durations_mode accurate;
		
		add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		expires 100d;
	}	
	
	# all unidentified requests fallback to api (inc. playManifest)
	location @api_fallback {
		proxy_pass http://kalapi;
		proxy_set_header Host $http_host;
	}
	
	#error_page  404			  /404.html;

	# redirect server error pages to the static page /50x.html
	#
	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
		root   html;
	}

            location /dashme {
                    open_file_cache off;
                    root /var/tmp;
                    add_header Cache-Control no-cache;
                    # To avoid issues with cross-domain HTTP requests (e.g. during development)
                    add_header Access-Control-Allow-Origin *;
            }
            location /hlsme {
                    open_file_cache off;
                    types {
                            application/vnd.apple.mpegurl m3u8;
                    }
                    root /var/tmp;
                    add_header Cache-Control no-cache; # Prevent caching of HLS fragments
                    add_header Access-Control-Allow-Origin *; # Allow web player to access our playlist
            }
And it doesn't work when I try with load balancer url like this. http://2.rectvideo.tk/hls/d1/cdn4/movies/hd/mp4/12yillik.mp4/index.m3u8

**Comment by erankor** [comment]
one question - why here?!

**Comment by erdi2202** [comment]
Where should I write?

**Comment by erdi2202** [comment]
> one question - why here?!

Where should I write?

**Comment by cclauss** [comment]
In a new issue: https://github.com/kaltura/nginx-vod-module/issues/new

**Pull request merged**
