### PR TITLE
Fix warnings treaded as errors when compiling

### PR DESCRIPTION
**Pull request by lundberg**
Not able to build nginx debian package under ubuntu 14.04.
This fix removes compile warnings that were treated as errors due to `-Werror`

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @lundberg,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by kaltura-hooks** [comment]
Hi @lundberg,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Hi @lundberg, 

Why did you add ctype.h ? was it because of isspace used in ngx_simple_json_parser.c ?
If so, please move the include to the c file

Thanks !

**Comment by lundberg** [comment]
Exactly @erankor, `isspace` is the reason.
Updated pull request as you wanted.

**Comment by jessp01** [comment]
Thanks, Jonas. Please be sure to sign our CLA so we can merge.

May the source be with you,

Jess Portnoy

**Comment by kaltura-hooks** [comment]
Hi @lundberg,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Pull request merged**
